config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions:      'devise/admins/sessions',
    passwords:     'devise/admins/passwords',
    registrations: 'devise/admins/registrations'
  }
  devise_for :customers, controllers: {
    sessions:      'devise/customers/sessions',
    passwords:     'devise/customers/passwords',
    registrations: 'devise/customers/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admin do
    # topページHomeに変更
    get '/' => 'homes#top'
    resources :items, except: [:destroy]
    
    resources :categories, except: [:destroy, :show, :new]
    resources :customers, except: [:destroy, :new, :create]
    get "search" => "customers#search"
    
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
    
  end

  scope module: :public do
    resource :homes, only: [:top, :about]
    resources :items, only: [:index, :show] do
      member do
        get "search" => "items#search"   #<=サーチアクション
      end
    end
    #resouceだとurlが複数形になるため  resource => resources
    resources :customers, only: [:show, :edit, :update]      # <= current_userで:id不要？
    get "customer/:id/unsubscribe" => "customers#unsubscribe", as: 'customer_unsubscribe'
    patch 'customer/:id/withdraw' => 'customers#withdraw', as: 'customer_withdraw'
    resources :cart_items, except: [:new, :show, :edit] do
      collection do    #<=追加cart_item

        delete "all_destroy"
      end
    end

    resources :orders, except: [:destroy, :edit, :update] do
    member do
    get "complete"
    end
    end

    post "orders/confirm" => "orders#confirm"
    resources :shippings, except: [:new, :show]

    root to: "homes#top"
    get 'home/about' => 'homes#about'
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

validates :quantity, presence: true

  def subtotal_price #<=小計を求める,こいつが動いてくれるかわからない
    tax_price * quantity.to_i
  end

  def tax_price
     item.price * 1.1
  end
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :items, dependent: :destroy
  
  validates :name, presence: true, uniqueness: true

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shippings, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :items, through: :cart_items
  has_many :cart_items


#   admin側の検索機能
  def Customer.search(search, customer_or_item)
    if customer_or_item == "1"
       Customer.where(['family_name LIKE ?', "%#{search}%"])
    else
       Customer.all
    end
  end


  validates :family_name, presence: true
  validates :first_name, presence: true
  VALID_KANA_REGEX = /\A[\p{katakana}\p{blank}ー－]+\z/
  validates :kana_family_name, presence: true, format: { with: VALID_KANA_REGEX }
  validates :kana_first_name, presence: true,  format: { with: VALID_KANA_REGEX }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :zipcode, presence: true
  validates :address, presence: true
  VALID_PHONE_NUMBER_REGEX = /\A0(\d{1}[-(]?\d{4}|\d{2}[-(]?\d{3}|\d{3}[-(]?\d{2}|\d{4}[-(]?\d{1})[-)]?\d{4}\z|\A0[5789]0[-]?\d{4}[-]?\d{4}\z/
  validates :phone_number, presence: true, format: { with: VALID_PHONE_NUMBER_REGEX }

  # enum is_deleted: { '有効': false, '退会済': true }

  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :category
  has_many :order_details, dependent: :destroy
  has_many :customers, through: :cart_items
  # order_detailsも中間テーブルだと思ったので、新規で追加しました
  has_many :orders, through: :order_details
  has_many :cart_items

  attachment :image
  
  validates :name, presence: true, uniqueness: true
  validates :introduction, :category_id, :price, :is_active, presence: true

#   admin側の検索機能（ヘッダー部分）
  def Item.search(search, customer_or_item)
    if customer_or_item == "2"
    Item.where(['name LIKE ?', "%#{search}%"])
    else
    Item.all
    end
  end


end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details, dependent: :destroy

validates :zipcode, presence: true
validates :address, presence: true
validates :name, presence: true


enum payment:{  #<=遠い未来で日本語化をします（今は仮定の日本語）
  "銀行振込": 0,
  "クレジットカード": 1
} 

enum status:{
  "入金待ち": 0,
  "入金確認": 1,
  "製作中": 2,
  "発送準備": 3,
  "発送済み": 4
}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :item
  belongs_to :order

enum product_status:{
  "制作不可": 0,
  "制作待ち": 1,
  "製作中": 2,
  "制作完了": 3
}



def total_price
  price * quantity
end
end

app/models/shipping.rb
class Shipping < ApplicationRecord

  belongs_to :customer

def shipping_address
zipcode + address + name
end

  validates :name, presence: true
  validates :zipcode, presence: true
  validates :address, presence: true

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
    before_action :authenticate_admin!
    
    def index
        @customers = Customer.all.page(params[:page]).per(10)
    end
    
    def show
        @customer = Customer.find(params[:id])
    end
    
    def edit 
        @customer = Customer.find(params[:id])
    end
    
    def update
        @customer = Customer.find(params[:id])
        if @customer.update(customer_params)
            redirect_to admin_customer_path(@customer.id)
        else
            render :edit
        end
    end
    
    def search
        @customers = Customer.all
        @customer_or_item = params[:option]
        if @customer_or_item == "1"
        @customers = Customer.search(params[:search], @customer_or_item)
        else
        @items = Item.search(params[:search], @customer_or_item)
        end
    end    
    
    private
    def customer_params
         params.require(:customer).permit(:family_name, :first_name, :kana_family_name, :kana_first_name, :zipcode, :address, :phone_number, :email, :is_deleted)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
     before_action :configure_permitted_parameters, if: :devise_controller?

# ログイン時に遷移するpathを設定
    def after_sign_in_path_for(resource)
            root_path
    end

# ログアウト後に遷移するpathを設定
    def after_sign_out_path_for(resource)
        root_path
    end


    def configure_permitted_parameters
      if resource_class == Customer
            devise_parameter_sanitizer.permit(:sign_up, keys: [:family_name,:first_name,:kana_family_name,:kana_first_name,:zipcode,:address,:phone_number,:email])
            devise_parameter_sanitizer.permit(:sign_in,keys:[:email])
            devise_parameter_sanitizer.permit(:account_update,keys:[:name,:email])
      end
    end
end

app/controllers/cart_items_controller.rb
class public::CartItemsController < ApplicationController
  
#カート内商品一覧
def index
end

#カート内商品追加
def create
end

#カート内商品個数変更
def update
end

#カート内商品削除
def destroy
end

#カートをからにする
def destroy_all
end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
end

app/controllers/shippings_controller.rb
class ShippingsController < ApplicationController
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/shippings_helper.rb
module ShippingsHelper
end

app/views/admin/customers/edit.html.erb
<%= form_with model: @customer, url: admin_customer_path, method: :put, local: true do |f| %>
<div class='container'>
    <div class="row mt-5 ml-5">
        <!--エラーメッセージの呼び出し-->
        <%= render "layouts/error_messages", model: @customer %>
        <h2 class="heading"><%= @customer.family_name %>     <%= @customer.first_name %>さんの会員情報編集</h2>
    </div>
    <div class='row'>
        <div class="col-lg-7 mx-auto mt-3">
            <table class="table table-borderless">
                <tr>
                    <td><%= f.label :"顧客ID" %></td>
                    <td><%= @customer.id %></td>
                </tr>
                <tr>
                    <td><%= f.label :"氏名" %></td>
                    <td><%= f.text_field :family_name, class: "form-control"  %></td>
                    <td><%= f.text_field :first_name, class: "form-control"  %></td>
                </tr>
                <tr>
                    <td><%= f.label :"フリガナ" %></td>
                    <td><%= f.text_field :kana_family_name, class: "form-control"  %></td>
                    <td><%= f.text_field :kana_first_name , class: "form-control" %></td>
                </tr>
                <tr>
                    <td><%= f.label :"郵便番号" %></td>
                    <td><%= f.text_field :zipcode , class: "form-control" %></td>
                </tr>
                <tr>
                    <td><%= f.label :"住所" %></td>
                    <td><%= f.text_area :address, class: "form-control"  %></td>
                </tr>
                <tr>
                    <td><%= f.label :"電話番号" %></td>
                    <td><%= f.text_field :phone_number, class: "form-control"  %></td>
                </tr>
                <tr>
                    <td><%= f.label :"メールアドレス" %></td>
                    <td><%= f.text_field :email, class: "form-control"  %></td>
                </tr>
                <tr>
                    <td></td>
                    <td><%= f.radio_button :is_deleted, false %>有効
                        <%= f.radio_button :is_deleted, true %>退会済み</td>
                </tr>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-sm-12 text-center mt-4">
            <%= f.submit "変更を保存する", class: "btn btn-secondary" %>
        </div>
    </div>
</div>
<% end %>

app/views/admin/customers/index.html.erb
<div class='container'>
    <div class='row mt-5 ml-5'>
        <h2 class="heading">会員一覧</h2>
    </div>
    <div class="row">
        <div class="col-lg-10 mx-auto mt-3">
            <table class="table table-bordered">
                <thead class='thead-light'>
                    <tr class="table-name">
                        <th>会員ID</th>
                        <th>氏名</th>
                        <th>メールアドレス</th>
                        <th>ステータス</th>
                    </tr>
                </thead>
                <tbody>
                <!--テーブルの中身-->
                <% @customers.each do |customer| %>
                    <tr>
                        <td><%= customer.id %></td>
                        <td><%= link_to admin_customer_path(customer.id) do %>
                            <%= customer.family_name %>                         <%= customer.first_name %> 
                            <% end %></td>
                        <td><%= customer.email %></td>
                        <% if customer.is_deleted == false %>
                            <td>有効</td>
                        <% elsif customer.is_deleted == true %>
                            <td>退会済み</td>
                        <% end %>
                    </tr>
                <% end %>
                </tbody>
            </table>
        </div>
       
    </div>
    <div class='row'>
        <div class="col">
          <div class="d-flex align-items-center justify-content-center">
            <%= paginate @customers %>
          </div>
        </div>
      </div>
</div>

app/views/admin/customers/search.html.erb
<div class='container'>
    <div class='row'>
      <% if @customer_or_item == "1" %>
        <h2>会員一覧</h2>
          <table class="table">
            <thead>
                <tr class="table-name">
                    <th>会員ID</th>
                    <th>氏名</th>
                    <th>メールアドレス</th>
                    <th>ステータス</th>
                </tr>
            </thead>
            <tbody>
                <% @customers.each do |customer| %>
                <tr>
                    <td><%= customer.id %></td>
                    <td><%= link_to admin_customer_path(customer.id) do %>
                        <%= customer.family_name %>                         <%= customer.first_name %> 
                        <% end %></td>
                    <td><%= customer.email %></td>
                    <% if customer.is_deleted == false %>
                        <td>有効</td>
                    <% elsif customer.is_deleted == true %>
                        <td>退会済み</td>
                    <% end %>
                </tr>
                <% end %>
            </tbody>
        </table>

    <% elsif @customer_or_item == "2" %>
    
     <h2>商品一覧</h2>
 
 <table class="table">
        <thead>
          <tr class='table-name'>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
            <tr>
              <td><%= item.id %></td>
              <td><%= link_to admin_item_path(item.id) do %>
                  <%= item.name %>
                  <% end %></td>
              <td><%= item.price %></td>
              <td><%= item.category.name %></td>
              <% if item.is_active == true %>
                <td>販売中</td>
                <% elsif item.is_active == false %>
                <td>売切れ</td>
                <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    
  
<% else %>
<% end %>
    </div>
</div>

app/views/admin/customers/show.html.erb
<div class='container'>
    <div class="row mt-5 ml-5">
        <h2 class="heading"><%= @customer.family_name %>     <%= @customer.first_name %>  さんの会員詳細</h2>
        <div class="customer_status ml-5">
            <% if @customer.is_deleted == true %>
                <bottun class="btn btn-danger">退会済み</bottun>
            <% elsif @customer.is_deleted == false %>
                <bottun class="btn btn-success">有効</bottun>
            <% end %>
        </div>
    </div>
    <div class='row'>
        <div class="col-lg-7 mx-auto mt-3">
            <table class="table table-bordered">
                <tr>
                    <td>顧客ID</td>
                    <td><%= @customer.id %>
                        
                    </td>
                </tr>
                
                <tr>
                    <td>氏名</td>
                    <td><%= @customer.family_name %>
                    <%= @customer.first_name %></td>
                </tr>
                <tr>
                    <td>フリガナ</td>
                    <td><%= @customer.kana_family_name %>
                    <%= @customer.kana_first_name %></td>
                </tr>
                <tr>
                    <td>郵便番号</td>
                    <td><%= @customer.zipcode %></td>
                </tr>
                <tr>
                    <td>住所</td>
                    <td><%= @customer.address %></td>
                </tr>
                <tr>
                    <td>電話番号</td>
                    <td><%= @customer.phone_number %></td>
                </tr>
                <tr>
                    <td>メールアドレス</td>
                    <td><%= @customer.email %></td>
                </tr>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-sm-12 text-center mt-4">
            <%= link_to "編集する", edit_admin_customer_path, class: "btn btn-secondary" %>
            <%= link_to "注文履歴一覧をみる", admin_orders_path, class: "btn btn-secondary ml-5" %>
        </div>
    </div>
</div>