config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions:      'devise/admins/sessions',
    passwords:     'devise/admins/passwords',
    registrations: 'devise/admins/registrations'
  }
  devise_for :customers, controllers: {
    sessions:      'devise/customers/sessions',
    passwords:     'devise/customers/passwords',
    registrations: 'devise/customers/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admin do
    # topページHomeに変更
    get '/' => 'homes#top'
    resources :items, except: [:destroy]
    
    resources :categories, except: [:destroy, :show, :new]
    resources :customers, except: [:destroy, :new, :create]
    get "search" => "customers#search"
    
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
    
  end

  scope module: :public do
    resource :homes, only: [:top, :about]
    resources :items, only: [:index, :show] do
      member do
        get "search" => "items#search"   #<=サーチアクション
      end
    end
    #resouceだとurlが複数形になるため  resource => resources
    resources :customers, only: [:show, :edit, :update]      # <= current_userで:id不要？
    get "customer/:id/unsubscribe" => "customers#unsubscribe", as: 'customer_unsubscribe'
    patch 'customer/:id/withdraw' => 'customers#withdraw', as: 'customer_withdraw'
    resources :cart_items, except: [:new, :show, :edit] do
      collection do    #<=追加cart_item

        delete "all_destroy"
      end
    end

    resources :orders, except: [:destroy, :edit, :update] do
    member do
    get "complete"
    end
    end

    post "orders/confirm" => "orders#confirm"
    resources :shippings, except: [:new, :show]

    root to: "homes#top"
    get 'home/about' => 'homes#about'
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

validates :quantity, presence: true

  def subtotal_price #<=小計を求める,こいつが動いてくれるかわからない
    tax_price * quantity.to_i
  end

  def tax_price
     item.price * 1.1
  end
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :items, dependent: :destroy
  
  validates :name, presence: true, uniqueness: true

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shippings, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :items, through: :cart_items
  has_many :cart_items


#   admin側の検索機能
  def Customer.search(search, customer_or_item)
    if customer_or_item == "1"
       Customer.where(['family_name LIKE ?', "%#{search}%"])
    else
       Customer.all
    end
  end


  validates :family_name, presence: true
  validates :first_name, presence: true
  VALID_KANA_REGEX = /\A[\p{katakana}\p{blank}ー－]+\z/
  validates :kana_family_name, presence: true, format: { with: VALID_KANA_REGEX }
  validates :kana_first_name, presence: true,  format: { with: VALID_KANA_REGEX }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :zipcode, presence: true
  validates :address, presence: true
  VALID_PHONE_NUMBER_REGEX = /\A0(\d{1}[-(]?\d{4}|\d{2}[-(]?\d{3}|\d{3}[-(]?\d{2}|\d{4}[-(]?\d{1})[-)]?\d{4}\z|\A0[5789]0[-]?\d{4}[-]?\d{4}\z/
  validates :phone_number, presence: true, format: { with: VALID_PHONE_NUMBER_REGEX }

  # enum is_deleted: { '有効': false, '退会済': true }

  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :category
  has_many :order_details, dependent: :destroy
  has_many :customers, through: :cart_items
  # order_detailsも中間テーブルだと思ったので、新規で追加しました
  has_many :orders, through: :order_details
  has_many :cart_items

  attachment :image
  
  validates :name, presence: true, uniqueness: true
  validates :introduction, :category_id, :price, :is_active, presence: true

#   admin側の検索機能（ヘッダー部分）
  def Item.search(search, customer_or_item)
    if customer_or_item == "2"
    Item.where(['name LIKE ?', "%#{search}%"])
    else
    Item.all
    end
  end


end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details, dependent: :destroy

validates :zipcode, presence: true
validates :address, presence: true
validates :name, presence: true


enum payment:{  #<=遠い未来で日本語化をします（今は仮定の日本語）
  "銀行振込": 0,
  "クレジットカード": 1
} 

enum status:{
  "入金待ち": 0,
  "入金確認": 1,
  "製作中": 2,
  "発送準備": 3,
  "発送済み": 4
}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :item
  belongs_to :order

enum product_status:{
  "制作不可": 0,
  "制作待ち": 1,
  "製作中": 2,
  "制作完了": 3
}



def total_price
  price * quantity
end
end

app/models/shipping.rb
class Shipping < ApplicationRecord

  belongs_to :customer

def shipping_address
zipcode + address + name
end

  validates :name, presence: true
  validates :zipcode, presence: true
  validates :address, presence: true

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
    before_action :authenticate_admin!
    
    def index
        @category = Category.new
        @categories = Category.all
    end
    
    def create
        @category = Category.new(category_params)
        @categories = Category.all
        if @category.save
            flash[:notice] = "カテゴリーを追加しました"
            redirect_to admin_categories_path
        else
            render :index
        end
    end
    
    def edit
        @category = Category.find(params[:id])
    end
    
    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
            flash[:success] = "カテゴリーを変更しました"
            redirect_to admin_categories_path(@category.id)
            if @category.is_active == false
                @category.items.each do |item|
                    item.is_active = false
                    item.save
                end
            end
        else
            render :edit
        end
    end
    
   
    
    private
    def category_params
        params.require(:category).permit(:name, :is_active)
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
     before_action :configure_permitted_parameters, if: :devise_controller?

# ログイン時に遷移するpathを設定
    def after_sign_in_path_for(resource)
            root_path
    end

# ログアウト後に遷移するpathを設定
    def after_sign_out_path_for(resource)
        root_path
    end


    def configure_permitted_parameters
      if resource_class == Customer
            devise_parameter_sanitizer.permit(:sign_up, keys: [:family_name,:first_name,:kana_family_name,:kana_first_name,:zipcode,:address,:phone_number,:email])
            devise_parameter_sanitizer.permit(:sign_in,keys:[:email])
            devise_parameter_sanitizer.permit(:account_update,keys:[:name,:email])
      end
    end
end

app/controllers/cart_items_controller.rb
class public::CartItemsController < ApplicationController
  
#カート内商品一覧
def index
end

#カート内商品追加
def create
end

#カート内商品個数変更
def update
end

#カート内商品削除
def destroy
end

#カートをからにする
def destroy_all
end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
end

app/controllers/shippings_controller.rb
class ShippingsController < ApplicationController
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/shippings_helper.rb
module ShippingsHelper
end

app/views/admin/categories/_form_category.html.erb
<%= form_with model: category, url:admin_categories_path, local:true do |f| %>
    <div class="col-lg-9 mx-auto">
        <table class="table table-borderless">
            <tr>
                <td><%= f.label :"カテゴリー" %></td>
                <td><%= f.text_field :name, class: "form-control" %></td>
            </tr>
            <tr>
                <td><%= f.radio_button :is_active, true %>有効
                    <%= f.radio_button :is_active, false %>無効</td>
            </tr>
            <tr>
                <td><%= f.submit "追加", class: "btn btn-secondary ml-3 mt-3" %></td>
            </tr>
        </table>
    </div>
<% end %>

app/views/admin/categories/edit.html.erb
<%= form_with model: @category, url: admin_category_path, local: true do |f| %>
<div class="container">
    <div class="row mt-5 ml-5">
        <!--エラーメッセージ呼び出し-->
        <%= render "layouts/error_messages", model: @category %>
        <h2 class="heading">カテゴリー編集</h2>
    </div>
    <div class="row">
        <div class="col-lg-6 mx-auto mt-5">
            <table class="table table-borderless">
                <tr>
                    <td><%= f.label :"カテゴリー" %></td>
                    <td> <%= f.text_field :name, class: "form-control" %></td>
                </tr>
                <tr>
                    <td><%= f.label :"状態" %></td>
                    <td><%= f.radio_button :is_active, true %>有効
                        <%= f.radio_button :is_active, false %>無効
                    </td>
                </tr>
            </table>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12 text-center mt-4">
            <%= f.submit "変更を保存する", class: "btn btn-secondary" %>
        </div>
    </div>
</div>
<% end %>

app/views/admin/categories/index.html.erb
<div class='container'>
    <div class="row mt-5 ml-5">
    <h2 class="heading">カテゴリー一覧・追加</h2>
    </div>
    <div class="row">
        <div class="col-lg-6 mx-auto mt-5">
        <!--エラーメッセージ呼び出し-->
        <%= render "layouts/error_messages", model: @category %>
        <!--カテゴリー新規追加フォーム呼び出し-->
        <%= render "form_category", category: @category %>
        
            <table class="table table-bordered text-center mt-5">
                <thead class='thead-light'>
                    <tr class="table-name">
                        <th>カテゴリー</th>
                        <th>状態</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody style="padding-bottom: 100px">
                <!--テーブルの中に表示させる値-->
                <% @categories.each do |category| %> 
                    <tr>
                    <% if category.is_active == true %>
                        <td><%= category.name %></td>
                        <td>有効</td>
                        <td><p><%= link_to "編集する", edit_admin_category_path(category.id), class: "btn btn-secondary" %></p></td>
                    <% end %>
                    </tr>
                <% end %>
                
                </tbody>
            </table>
        </div>
    </div>
</div>