config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions:      'devise/admins/sessions',
    passwords:     'devise/admins/passwords',
    registrations: 'devise/admins/registrations'
  }
  devise_for :customers, controllers: {
    sessions:      'devise/customers/sessions',
    passwords:     'devise/customers/passwords',
    registrations: 'devise/customers/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admin do
    # topページHomeに変更
    get '/' => 'homes#top'
    resources :items, except: [:destroy]
    
    resources :categories, except: [:destroy, :show, :new]
    resources :customers, except: [:destroy, :new, :create]
    get "search" => "customers#search"
    
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
    
  end

  scope module: :public do
    resource :homes, only: [:top, :about]
    resources :items, only: [:index, :show] do
      member do
        get "search" => "items#search"   #<=サーチアクション
      end
    end
    #resouceだとurlが複数形になるため  resource => resources
    resources :customers, only: [:show, :edit, :update]      # <= current_userで:id不要？
    get "customer/:id/unsubscribe" => "customers#unsubscribe", as: 'customer_unsubscribe'
    patch 'customer/:id/withdraw' => 'customers#withdraw', as: 'customer_withdraw'
    resources :cart_items, except: [:new, :show, :edit] do
      collection do    #<=追加cart_item

        delete "all_destroy"
      end
    end

    resources :orders, except: [:destroy, :edit, :update] do
    member do
    get "complete"
    end
    end

    post "orders/confirm" => "orders#confirm"
    resources :shippings, except: [:new, :show]

    root to: "homes#top"
    get 'home/about' => 'homes#about'
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

validates :quantity, presence: true

  def subtotal_price #<=小計を求める,こいつが動いてくれるかわからない
    tax_price * quantity.to_i
  end

  def tax_price
     item.price * 1.1
  end
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :items, dependent: :destroy
  
  validates :name, presence: true, uniqueness: true

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shippings, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :items, through: :cart_items
  has_many :cart_items


#   admin側の検索機能
  def Customer.search(search, customer_or_item)
    if customer_or_item == "1"
       Customer.where(['family_name LIKE ?', "%#{search}%"])
    else
       Customer.all
    end
  end


  validates :family_name, presence: true
  validates :first_name, presence: true
  VALID_KANA_REGEX = /\A[\p{katakana}\p{blank}ー－]+\z/
  validates :kana_family_name, presence: true, format: { with: VALID_KANA_REGEX }
  validates :kana_first_name, presence: true,  format: { with: VALID_KANA_REGEX }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :zipcode, presence: true
  validates :address, presence: true
  VALID_PHONE_NUMBER_REGEX = /\A0(\d{1}[-(]?\d{4}|\d{2}[-(]?\d{3}|\d{3}[-(]?\d{2}|\d{4}[-(]?\d{1})[-)]?\d{4}\z|\A0[5789]0[-]?\d{4}[-]?\d{4}\z/
  validates :phone_number, presence: true, format: { with: VALID_PHONE_NUMBER_REGEX }

  # enum is_deleted: { '有効': false, '退会済': true }

  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :category
  has_many :order_details, dependent: :destroy
  has_many :customers, through: :cart_items
  # order_detailsも中間テーブルだと思ったので、新規で追加しました
  has_many :orders, through: :order_details
  has_many :cart_items

  attachment :image
  
  validates :name, presence: true, uniqueness: true
  validates :introduction, :category_id, :price, :is_active, presence: true

#   admin側の検索機能（ヘッダー部分）
  def Item.search(search, customer_or_item)
    if customer_or_item == "2"
    Item.where(['name LIKE ?', "%#{search}%"])
    else
    Item.all
    end
  end


end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details, dependent: :destroy

validates :zipcode, presence: true
validates :address, presence: true
validates :name, presence: true


enum payment:{  #<=遠い未来で日本語化をします（今は仮定の日本語）
  "銀行振込": 0,
  "クレジットカード": 1
} 

enum status:{
  "入金待ち": 0,
  "入金確認": 1,
  "製作中": 2,
  "発送準備": 3,
  "発送済み": 4
}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :item
  belongs_to :order

enum product_status:{
  "制作不可": 0,
  "制作待ち": 1,
  "製作中": 2,
  "制作完了": 3
}



def total_price
  price * quantity
end
end

app/models/shipping.rb
class Shipping < ApplicationRecord

  belongs_to :customer

def shipping_address
zipcode + address + name
end

  validates :name, presence: true
  validates :zipcode, presence: true
  validates :address, presence: true

end

app/controllers/cart_items_controller.rb
class public::CartItemsController < ApplicationController
  
#カート内商品一覧
def index
end

#カート内商品追加
def create
end

#カート内商品個数変更
def update
end

#カート内商品削除
def destroy
end

#カートをからにする
def destroy_all
end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
end

app/controllers/shippings_controller.rb
class ShippingsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/shippings_helper.rb
module ShippingsHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header class="header">

    <nav class="navbar navbar-expand-lg navbar-light ma-auto">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
    


    
                <ul class="navbar-nav">
                <!--会員がログインしたとき-->
                <% if customer_signed_in? %>
                <p class="fas fa-bell", style="color:#F5F5F5"> ようこそ、<strong><%= current_customer.family_name %> <%= current_customer.first_name %></strong> さん！</p>
                <%= link_to root_path, class:"nav-link text-black" do %>
                <p class="logo-head"><%= image_tag 'logo-4.png', :size => '150x75' %></p>
                <% end %>
                <li class="nav-item">
                    <%= link_to "マイページ", customer_path(current_customer), class: 'btn btn-outline-secondary fas fa-user nav-link text-white' %>
                </li>
                <li class="nav-item">
                    <%= link_to "商品一覧", items_path, class: 'btn btn-outline-secondary fas fa-weight-hanging nav-link text-white' %>
                </li>
                <li class="nav-item">
                    <%= link_to "カート", cart_items_path, class: 'btn btn-outline-secondary fas fa-shopping-cart nav-link text-white' %>
                </li>
                <li class="nav-item">
                    <%= link_to "About", home_about_path, class: 'btn btn-outline-secondary fas fa-info nav-link text-white' %> 
                </li>
                <li class="nav-item">
                    <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'btn btn-outline-danger fas fa-sign-out-alt nav-link text-white' %>
                </li>

                  


                <!--管理人がログインしたとき-->
                <% elsif admin_signed_in? %>
                <%= link_to admin_path do %>
                <p class="logo-head"><%= image_tag 'logo-4.png', :size => '150x75' %></p>
                <% end %>
                <li class="nav-item">
                    <%= link_to "商品一覧", admin_items_path, class: 'fas fa-weight-hanging nav-link text-white' %>
                </li>
                <li class="nav-item">
                    <%= link_to "会員一覧", admin_customers_path, class: 'btn fas fa-users nav-link text-white' %>
                </li>
                <li class="nav-item">
                    <%= link_to "注文一覧", admin_orders_path, class: 'fas fa-store nav-link text-white' %>
                </li>
                <li class="nav-item">
                    <%= link_to "カテゴリ一覧", admin_categories_path, class: 'fas fa-certificate nav-link text-white' %>
                </li>
                <li class="nav-item">
                    <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-white' %>
                </li>
            
                <!--検索フォームの呼び出し-->
                <span>
                <%= render "layouts/search" %>
                </span>
                <% else %>
            
                <!--会員も管理人もログインしてないとき-->
                <%= link_to root_path do %>
                <p class="logo-head ml-5"><%= image_tag 'logo-4.png', :size => '150x75' %></p>
                <% end %>
                <li class="nav-item ml-5">
                    <%= link_to "About", home_about_path, class: 'btn btn-outline-secondary fas fa-info nav-link text-white' %> 
                </li>
                <li class="nav-item ml-5">
                    <%= link_to "商品一覧", items_path, class: 'btn btn-outline-secondary fas fa-weight-hanging nav-link text-white' %>
                </li>
                <li class="nav-item ml-5">
                    <%= link_to "新規登録", new_customer_registration_path, class: 'btn btn-outline-secondary fas fa-user-plus nav-link text-white' %>
                </li>
                <li class="nav-item ml-5">
                    <%= link_to "ログイン", new_customer_session_path, class: 'btn btn-outline-secondary fas fa-sign-in-alt nav-link text-white' %>
                </li>
                <% end %>
            </ul>
            </div>
    </nav>
</header>

app/views/layouts/_search.html.erb
 <div class="input-group">
  <%= form_with url: admin_search_path, method: :get, local:true do |f| %>
    <%= f.select :option, [["customer", "1"],["item","2"]] %>
    <%= f.text_field :search %>
    <span class="input-group-btn">
    <%= f.submit 'Search' %>
    </span>
    <% end %>
    </div>
    
    
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/31bd3b6efb.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <%= render "layouts/header" %>
    <div class='main'>
    <!--サクセスメッセージ呼び出し-->
       <p id="notice"><%= notice %></p>

    <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <footer class="text-white" style="bottom: 0">
    <p>© All rights reserved by Oimo</p>

    </footer>
  </body>
</html>